<?php
/**
 * MageHelper Magento 2 Enable Disable Toggle in Configuration.
 *
 * @package      MageHelper_ConfigEnableDisableToggle
 * @author       Kishan Savaliya <kishansavaliyakb@gmail.com>
 */
?>
<?php $configPath = $this->getConfigPath(); ?>
<?php $groupName = $this->getGroupName(); ?>
<?php $fieldName = $this->getFieldName(); ?>
<?php $inputFieldName = "groups[".$groupName."][fields][".$fieldName."][value]"; ?>
<?php $isEnabled = $this->helper('MageHelper\ConfigEnableDisableToggle\Helper\MageHelper')->getConfig($configPath); ?>

<label class="switch">
    <input type="checkbox" class="enable-disable-checkbox" name="<?php echo $inputFieldName; ?>" value="<?php echo $isEnabled; ?>">
    <span class="slider round" id="enable-disable-config"></span>
</label>
<span id="toggle">
    <span class="toggle-yes"><?php echo "&nbsp;&nbsp;  Yes"; ?></span>
    <span class="toggle-no"><?php echo "&nbsp;&nbsp;  No"; ?></span>
</span>

<style>
    .switch {
        position: relative;
        display: inline-block;
        width: 37px;
        height: 22px;
        vertical-align: middle;
    }

    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
        vertical-align: middle;
    }
    .sliderOne {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
        vertical-align: middle;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 22px;
        width: 22px;
        left: -7.75px;
        bottom: 0px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
        vertical-align: middle;
    }
    .sliderOne:before {
        position: absolute;
        content: "";
        height: 22px;
        width: 22px;
        left: .5px;
        bottom: 0px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
        vertical-align: middle;
    }

    input.checked-checkbox + .slider {
        background-color: #79a22e;
    }

    input:focus + .slider {
        box-shadow: 0 0 0px #2196F3;

    }

    input.checked-checkbox + .sliderOne {
        background-color: #79a22e;
    }

    input:focus + .sliderOne {
        box-shadow: 0 0 0px #2196F3;

    }

    input.checked-checkbox + .slider:before {
        -webkit-transform: translateX(22px);
        -ms-transform: translateX(22px);
        transform: translateX(22px);

    }
    input.checked-checkbox + .sliderOne:before {
        -webkit-transform: translateX(22px);
        -ms-transform: translateX(22px);
        transform: translateX(22px);

    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 35px;
    }

    .slider.round:before {
        border-radius: 100%;
        display: inline-block;
    }

    .sliderOne.round {
        border-radius: 35px;
    }

    .sliderOne.round:before {
        border-radius: 100%;
        display: inline-block;
    }
</style>

<script type="text/javascript">  
(function  () {    
    require(["jquery"], function($) {
        $(document).ready(function($) {

            var isEnabled = "<?php echo $isEnabled; ?>";

            if(isEnabled != 0){
                $(".enable-disable-checkbox").addClass("checked-checkbox");
                $("#enable-disable-config").addClass('sliderOne');
                $(".toggle-yes").show();
                $(".toggle-no").hide();
            }else{
                $(".toggle-yes").hide();
                $(".toggle-no").show();
            }

            $(".enable-disable-checkbox").on("click", function(e){
                if($("#enable-disable-config").hasClass('sliderOne')){
                    $(".enable-disable-checkbox").removeClass("checked-checkbox");
                    $("#enable-disable-config").removeClass('sliderOne');
                    $(".toggle-yes").hide();
                    $(".toggle-no").show();
                    $(".enable-disable-checkbox").attr('value', 0);
                }else{
                    $(".enable-disable-checkbox").addClass("checked-checkbox");
                    $("#enable-disable-config").addClass('sliderOne');
                    $(".toggle-yes").show();
                    $(".toggle-no").hide();
                    $(".enable-disable-checkbox").attr('value', 1);
                }
            });
        }); 
    });
})();
</script>